import type { Agent, MarketSignal, Neighbourhood, Scenario } from "./types";

export const disclaimer =
  "Concept demonstration using synthetic neighbourhood, customer, network, demographic, competitive, financial, and market data. Recommendations, financial values, coverage information, forecasts, and agent actions are simulated and are not company forecasts or production decisions.";

export const neighbourhoods: Neighbourhood[] = [
  {
    id: "brookfield",
    name: "Brookfield North",
    action: "UPGRADE",
    status: "Proposed",
    score: 94,
    confidence: 91,
    households: 6850,
    plannedHomes: 2400,
    addressableHouseholds: 4150,
    revenue: 12.8,
    investment: 4.7,
    payback: 31,
    growth: 96,
    network: 82,
    competitive: 88,
    penetration: 34,
    internetOpportunity: 92,
    wirelessOpportunity: 86,
    mobileAttach: 90,
    capitalEfficiency: 88,
    churnExposure: 43,
    mduOpportunity: 72,
    x: 69,
    y: 26,
    reasons: ["2,400 planned homes", "Low provider penetration", "Competitor fibre activity"],
  },
  {
    id: "lakeshore",
    name: "Lakeshore Landing",
    action: "BUILD",
    status: "Review",
    score: 89,
    confidence: 86,
    households: 5400,
    plannedHomes: 1800,
    addressableHouseholds: 3200,
    revenue: 9.6,
    investment: 4.1,
    payback: 34,
    growth: 91,
    network: 68,
    competitive: 63,
    penetration: 38,
    internetOpportunity: 86,
    wirelessOpportunity: 76,
    mobileAttach: 79,
    capitalEfficiency: 81,
    churnExposure: 35,
    mduOpportunity: 84,
    x: 48,
    y: 76,
    reasons: ["Waterfront intensification", "High MDU pipeline", "Strong digital demand"],
  },
  {
    id: "cedar",
    name: "Cedar Heights",
    action: "MARKET",
    status: "Approved",
    score: 86,
    confidence: 89,
    households: 7200,
    plannedHomes: 760,
    addressableHouseholds: 2800,
    revenue: 7.9,
    investment: 1.8,
    payback: 19,
    growth: 76,
    network: 94,
    competitive: 57,
    penetration: 44,
    internetOpportunity: 78,
    wirelessOpportunity: 84,
    mobileAttach: 88,
    capitalEfficiency: 94,
    churnExposure: 30,
    mduOpportunity: 48,
    x: 24,
    y: 33,
    reasons: ["Network ready", "High mobile whitespace", "Fast payback"],
  },
  {
    id: "westhaven",
    name: "Westhaven",
    action: "DEFEND",
    status: "Active",
    score: 83,
    confidence: 88,
    households: 8800,
    plannedHomes: 420,
    addressableHouseholds: 2600,
    revenue: 6.8,
    investment: 2.2,
    payback: 24,
    growth: 58,
    network: 87,
    competitive: 95,
    penetration: 51,
    internetOpportunity: 70,
    wirelessOpportunity: 68,
    mobileAttach: 71,
    capitalEfficiency: 84,
    churnExposure: 82,
    mduOpportunity: 55,
    x: 37,
    y: 48,
    reasons: ["Competitor promotion spike", "Churn exposure", "Valuable installed base"],
  },
  {
    id: "meadowview",
    name: "Meadowview",
    action: "SELL",
    status: "Approved",
    score: 81,
    confidence: 84,
    households: 6100,
    plannedHomes: 900,
    addressableHouseholds: 2450,
    revenue: 6.1,
    investment: 1.5,
    payback: 18,
    growth: 75,
    network: 91,
    competitive: 52,
    penetration: 46,
    internetOpportunity: 74,
    wirelessOpportunity: 81,
    mobileAttach: 85,
    capitalEfficiency: 91,
    churnExposure: 28,
    mduOpportunity: 40,
    x: 54,
    y: 40,
    reasons: ["Family household growth", "Channel capacity", "Mobile attach gap"],
  },
  {
    id: "riverstone",
    name: "Riverstone",
    action: "PARTNER",
    status: "Review",
    score: 78,
    confidence: 76,
    households: 3900,
    plannedHomes: 1400,
    addressableHouseholds: 2100,
    revenue: 5.8,
    investment: 2.6,
    payback: 35,
    growth: 88,
    network: 61,
    competitive: 49,
    penetration: 32,
    internetOpportunity: 80,
    wirelessOpportunity: 67,
    mobileAttach: 72,
    capitalEfficiency: 73,
    churnExposure: 22,
    mduOpportunity: 76,
    x: 79,
    y: 53,
    reasons: ["Developer partnership", "Greenfield growth", "Phased serviceability"],
  },
  {
    id: "junction",
    name: "East Junction",
    action: "UPGRADE",
    status: "Proposed",
    score: 76,
    confidence: 82,
    households: 9100,
    plannedHomes: 680,
    addressableHouseholds: 2300,
    revenue: 5.4,
    investment: 2.5,
    payback: 33,
    growth: 66,
    network: 72,
    competitive: 76,
    penetration: 49,
    internetOpportunity: 69,
    wirelessOpportunity: 73,
    mobileAttach: 75,
    capitalEfficiency: 70,
    churnExposure: 61,
    mduOpportunity: 80,
    x: 66,
    y: 64,
    reasons: ["MDU density", "Capacity constraint", "Competitive urgency"],
  },
  {
    id: "maple",
    name: "Maple Ridge",
    action: "MARKET",
    status: "Active",
    score: 74,
    confidence: 85,
    households: 7600,
    plannedHomes: 510,
    addressableHouseholds: 1950,
    revenue: 4.9,
    investment: 1.4,
    payback: 22,
    growth: 62,
    network: 90,
    competitive: 55,
    penetration: 47,
    internetOpportunity: 71,
    wirelessOpportunity: 69,
    mobileAttach: 73,
    capitalEfficiency: 89,
    churnExposure: 26,
    mduOpportunity: 35,
    x: 17,
    y: 62,
    reasons: ["Ready capacity", "Digital intent", "Efficient acquisition"],
  },
  {
    id: "harbour",
    name: "Harbour Point",
    action: "DEFEND",
    status: "Monitoring",
    score: 71,
    confidence: 80,
    households: 8300,
    plannedHomes: 1050,
    addressableHouseholds: 1700,
    revenue: 4.4,
    investment: 1.9,
    payback: 29,
    growth: 71,
    network: 84,
    competitive: 89,
    penetration: 58,
    internetOpportunity: 64,
    wirelessOpportunity: 60,
    mobileAttach: 66,
    capitalEfficiency: 75,
    churnExposure: 77,
    mduOpportunity: 92,
    x: 39,
    y: 84,
    reasons: ["Fibre overbuild", "Premium MDU base", "Retention priority"],
  },
  {
    id: "university",
    name: "University District",
    action: "SELL",
    status: "Active",
    score: 68,
    confidence: 79,
    households: 4700,
    plannedHomes: 600,
    addressableHouseholds: 1550,
    revenue: 3.8,
    investment: 1.1,
    payback: 20,
    growth: 69,
    network: 88,
    competitive: 68,
    penetration: 53,
    internetOpportunity: 66,
    wirelessOpportunity: 78,
    mobileAttach: 82,
    capitalEfficiency: 86,
    churnExposure: 48,
    mduOpportunity: 88,
    x: 58,
    y: 18,
    reasons: ["Student mobility", "Wireless demand", "High MDU turnover"],
  },
  {
    id: "pinecrest",
    name: "Pinecrest",
    action: "MONITOR",
    status: "Monitoring",
    score: 58,
    confidence: 72,
    households: 4300,
    plannedHomes: 310,
    addressableHouseholds: 980,
    revenue: 2.4,
    investment: 1.2,
    payback: 39,
    growth: 51,
    network: 70,
    competitive: 45,
    penetration: 55,
    internetOpportunity: 52,
    wirelessOpportunity: 57,
    mobileAttach: 58,
    capitalEfficiency: 61,
    churnExposure: 24,
    mduOpportunity: 30,
    x: 83,
    y: 78,
    reasons: ["Moderate growth", "Limited urgency", "Watch permit activity"],
  },
  {
    id: "greenfield",
    name: "Greenfield South",
    action: "DEFER",
    status: "Monitoring",
    score: 46,
    confidence: 68,
    households: 2800,
    plannedHomes: 210,
    addressableHouseholds: 610,
    revenue: 1.5,
    investment: 1.3,
    payback: 52,
    growth: 43,
    network: 55,
    competitive: 38,
    penetration: 57,
    internetOpportunity: 44,
    wirelessOpportunity: 48,
    mobileAttach: 50,
    capitalEfficiency: 42,
    churnExposure: 20,
    mduOpportunity: 22,
    x: 15,
    y: 18,
    reasons: ["Low near-term density", "Long payback", "Build dependency"],
  },
];

export const signals: MarketSignal[] = [
  {
    id: 1,
    title: "New 820-unit housing development approved",
    category: "Housing",
    geography: "Brookfield North",
    confidence: 96,
    recency: "18 min ago",
    importance: "Critical",
    product: "Internet",
    agent: "Market Signal Agent",
    kind: "Opportunity",
    source: "Public",
    why: "Adds a concentrated early-acquisition window before first occupancy.",
    action: "Validate serviceability and engage the property developer.",
    privacy: "Aggregated municipal record; permitted for this simulated demonstration.",
  },
  {
    id: 2,
    title: "Competitor fibre construction detected",
    category: "Competitive",
    geography: "Brookfield North",
    confidence: 88,
    recency: "42 min ago",
    importance: "Critical",
    product: "Internet",
    agent: "Competitive Intelligence Agent",
    kind: "Risk",
    source: "Simulated",
    why: "Narrows the window to establish household relationships.",
    action: "Accelerate a targeted upgrade and early mover campaign.",
    privacy: "Synthetic competitive intelligence; production use would require validation.",
  },
  {
    id: 3,
    title: "Mobile attach is 14 points below comparable areas",
    category: "Commercial",
    geography: "Cedar Heights",
    confidence: 91,
    recency: "1 hr ago",
    importance: "High",
    product: "Wireless",
    agent: "Commercial Growth Agent",
    kind: "Opportunity",
    source: "Internal",
    why: "Existing Internet households present a high-efficiency cross-sell audience.",
    action: "Prepare an approved Internet plus mobile household journey.",
    privacy: "Aggregated neighbourhood-level synthetic data; no customer records.",
  },
  {
    id: 4,
    title: "School enrolment forecast increased",
    category: "Demographic",
    geography: "Meadowview",
    confidence: 82,
    recency: "2 hrs ago",
    importance: "Medium",
    product: "Wi-Fi",
    agent: "Market Signal Agent",
    kind: "Opportunity",
    source: "Public",
    why: "Supports the family-formation and household-connectivity demand thesis.",
    action: "Increase family segment demand assumptions for review.",
    privacy: "Aggregated public planning data; licensing review required for production.",
  },
  {
    id: 5,
    title: "Internet serviceability expansion completed",
    category: "Network",
    geography: "Maple Ridge",
    confidence: 97,
    recency: "3 hrs ago",
    importance: "High",
    product: "Internet",
    agent: "Network Readiness Agent",
    kind: "Opportunity",
    source: "Internal",
    why: "Converts market interest into an immediately addressable acquisition pool.",
    action: "Release the area for marketing readiness review.",
    privacy: "Synthetic network aggregate; operational controls still apply.",
  },
  {
    id: 6,
    title: "High volume of address-availability checks detected",
    category: "Digital",
    geography: "Lakeshore Landing",
    confidence: 85,
    recency: "4 hrs ago",
    importance: "High",
    product: "Internet",
    agent: "Commercial Growth Agent",
    kind: "Opportunity",
    source: "Internal",
    why: "Signals active household consideration before a formal launch.",
    action: "Assess a consented lead-capture and launch-notification journey.",
    privacy: "Aggregated digital activity; permitted-purpose review required.",
  },
  {
    id: 7,
    title: "Installation capacity available for incremental demand",
    category: "Operations",
    geography: "Brookfield North",
    confidence: 93,
    recency: "Today",
    importance: "High",
    product: "All",
    agent: "Network Readiness Agent",
    kind: "Opportunity",
    source: "Internal",
    why: "Reduces launch execution risk during the first occupancy wave.",
    action: "Reserve planning capacity subject to human approval.",
    privacy: "Synthetic operational capacity; no action has been executed.",
  },
  {
    id: 8,
    title: "Aggressive introductory pricing observed",
    category: "Competitive",
    geography: "Westhaven",
    confidence: 79,
    recency: "Yesterday",
    importance: "High",
    product: "Internet",
    agent: "Competitive Intelligence Agent",
    kind: "Risk",
    source: "Licensed",
    why: "Raises near-term churn and acquisition-cost pressure.",
    action: "Review approved retention and value communication options.",
    privacy: "Illustrative licensed source; procurement validation required.",
  },
];

export const agents: Agent[] = [
  {
    name: "Growth Planning Supervisor",
    shortName: "Supervisor",
    task: "Orchestrate evidence and resolve recommendations",
    confidence: 91,
    data: "All specialist findings",
    output: "Scenario B recommended with human approval",
  },
  {
    name: "Market Signal Agent",
    shortName: "Market",
    task: "Validate growth and development signals",
    confidence: 94,
    data: "Permits, housing, schools, digital intent",
    output: "2,400-home growth event validated",
  },
  {
    name: "Network Readiness Agent",
    shortName: "Network",
    task: "Assess serviceability and delivery feasibility",
    confidence: 89,
    data: "Coverage, capacity, proximity, field readiness",
    output: "Targeted upgrade is operationally feasible",
  },
  {
    name: "Competitive Intelligence Agent",
    shortName: "Competitive",
    task: "Assess competitive urgency",
    confidence: 84,
    data: "Fibre activity, promotions, estimated share",
    output: "Early-mover window is narrowing",
  },
  {
    name: "Commercial Growth Agent",
    shortName: "Commercial",
    task: "Estimate household and product opportunity",
    confidence: 90,
    data: "Penetration, attach, segment demand",
    output: "2,900 acquisition and 1,650 mobile-line opportunities",
  },
  {
    name: "Investment and ROI Agent",
    shortName: "Investment",
    task: "Compare scenarios and test economics",
    confidence: 87,
    data: "Investment, revenue, margin, risk",
    output: "2.7x revenue-to-investment ratio; 31-month payback",
  },
];

export const scenarios: Scenario[] = [
  {
    id: "A",
    name: "Market only",
    action: "Launch a commercial campaign using current serviceability",
    investment: 1.6,
    revenue: 6.1,
    payback: 19,
    customers: 1370,
    risk: "Capacity limits upside",
    confidence: 82,
  },
  {
    id: "B",
    name: "Targeted upgrade + launch",
    action: "Upgrade priority zones and coordinate neighbourhood acquisition",
    investment: 4.7,
    revenue: 12.8,
    payback: 31,
    customers: 2900,
    risk: "Moderate delivery risk",
    confidence: 91,
  },
  {
    id: "C",
    name: "Full accelerated build",
    action: "Build the complete planned footprint ahead of occupancy",
    investment: 8.9,
    revenue: 15.4,
    payback: 47,
    customers: 3420,
    risk: "High capital timing risk",
    confidence: 74,
  },
  {
    id: "D",
    name: "Defer and monitor",
    action: "Wait for demand and competitive signals to mature",
    investment: 0.4,
    revenue: 2.2,
    payback: 28,
    customers: 510,
    risk: "Lost early-mover position",
    confidence: 67,
  },
];

export const productOpportunity = [
  { name: "Home Internet", value: 5.8, colour: "#e11d48" },
  { name: "Mobile lines", value: 4.1, colour: "#2563eb" },
  { name: "Premium Wi-Fi", value: 1.6, colour: "#8b5cf6" },
  { name: "Other products", value: 1.3, colour: "#10b981" },
];

export const workflow = [
  "Signal detected",
  "Market validation",
  "Network feasibility",
  "Competitive assessment",
  "Commercial opportunity",
  "Investment analysis",
  "Supervisor recommendation",
  "Human approval",
  "Growth plan created",
  "Outcome monitoring",
];

export const workstreams = [
  { name: "Network", owner: "Regional Network Planning", progress: 42, gate: "Field design approval", tasks: "Validate design, confirm capital, reserve capacity, sequence upgrade" },
  { name: "Marketing", owner: "Consumer Growth Marketing", progress: 28, gate: "Campaign and privacy approval", tasks: "Define segments, propositions, launch timing, measurement" },
  { name: "Sales & channels", owner: "Omnichannel Sales", progress: 22, gate: "Channel readiness", tasks: "Prepare journeys, retail, call centre, field sales and lead routing" },
  { name: "Product", owner: "Internet & Wireless Product", progress: 35, gate: "Offer validation", tasks: "Confirm eligibility, approved offers, bundles and attach journeys" },
  { name: "Finance", owner: "Consumer Finance", progress: 18, gate: "Investment envelope", tasks: "Validate assumptions, approve envelope, establish benefit tracking" },
  { name: "Governance", owner: "Data & AI Governance", progress: 48, gate: "Permitted-use review", tasks: "Privacy, data rights, model review, audit and monitoring controls" },
];

export const walkthrough = [
  {
    title: "Growth decisions are fragmented across functions and data sources.",
    text: "Housing growth, customer demand, network readiness, competitive activity, marketing performance, and capital planning may be examined separately. The agent creates one evidence-backed decision frame.",
    metric: "6 signal domains connected",
  },
  {
    title: "The agent system continuously scans for neighbourhood-level change.",
    text: "The Market Signal Agent combines permitted internal, public, licensed, partner, and simulated signals, then assigns confidence to emerging opportunities.",
    metric: "186 neighbourhoods evaluated",
  },
  {
    title: "Brookfield North moves to the top of the portfolio.",
    text: "The system identifies 2,400 planned homes, family formation, strong connectivity demand, low penetration, nearby infrastructure, and competitive fibre activity.",
    metric: "94 opportunity score",
  },
  {
    title: "Each agent evaluates the opportunity from a different business perspective.",
    text: "Network, competitive, commercial, market, and investment specialists contribute findings while the Supervisor resolves the combined recommendation.",
    metric: "6 agents • 91% confidence",
  },
  {
    title: "Executives receive choices, not a black-box answer.",
    text: "Market-only, targeted upgrade, accelerated build, and defer scenarios expose investment, expected revenue, payback, customer opportunity, risk, and confidence.",
    metric: "Scenario B leads",
  },
  {
    title: "The agent recommends a coordinated network and commercial move.",
    text: "A targeted network upgrade is paired with an early neighbourhood launch focused on home Internet, mobile attachment, and premium whole-home Wi-Fi.",
    metric: "$12.8M illustrative revenue",
  },
  {
    title: "Agents recommend. Business leaders decide.",
    text: "The agent does not commit capital, launch a campaign, or change a network. Material decisions remain with authorized leaders and existing operating controls.",
    metric: "2 human approval gates",
  },
  {
    title: "A decision becomes a coordinated growth plan.",
    text: "Once approved for planning, linked workstreams align network, marketing, channels, product, finance, and governance around the same opportunity.",
    metric: "6 coordinated workstreams",
  },
  {
    title: "The business can connect every investment to measurable household growth.",
    text: "The outcome centre tracks acquisition, mobile attachment, multi-product growth, investment, payback, market share, customer experience, and execution speed.",
    metric: "24 monitored outcomes",
  },
  {
    title: "From annual territory planning to continuous market intelligence.",
    text: "The business can identify emerging markets earlier, align network and commercial investment, and measure whether each neighbourhood plan delivers the expected result.",
    metric: "Find • Validate • Approve • Measure",
  },
];
